### ISSUE TITLE
Error when converting to VOC

### ISSUE THREAD

**Issue by lonnylundsten** [kevinsbarnard/m3-download#3]
I often get errors like this when I convert to VOC. The current solution is to delete all localizations from the localizations.json file associated with the offending image reference uuid. The image actually exists so I'm not sure what the problem is. This is an example is from Psolus squamatus with the -d and -a flags, in case you want to reproduce the error.

Traceback (most recent call last):
  File "/Users/lonny/Documents/Code/Python/4_m3-download/reformat.py", line 103, in <module>
    main(_args.localizations, _output, _args.format.upper(), _args.voc_images)
  File "/Users/lonny/Documents/Code/Python/4_m3-download/reformat.py", line 71, in main
    annotation_record.add_annotation(iruuid, locs, voc_images)
  File "/Users/lonny/Documents/Code/Python/4_m3-download/lib/localization.py", line 278, in add_annotation
    raise ValueError(f'No image found for image reference UUID {image_reference_uuid}')
ValueError: No image found for image reference UUID be75ebb2-0027-4ccb-8027-3b7bf33a0a54

**Comment by kevinsbarnard** [comment]
This issue came from the fact that the `image_reference_uuid` as listed in the localization JSON in VARS does not necessarily correspond to an image reference for the imaged moment to which the localization is associated. I've reworked the system of passing image reference information through, so this should be working now.
