### ISSUE TITLE
generate digest fails for large searches

### ISSUE THREAD

**Issue by lonnylundsten** [kevinsbarnard/m3-download#4]
When doing a search for a large class and descendants, for example Actiniaria with the flags -a -d, the generate digest job fails without much indication as to what's going on. 1) I would like to be able to do this on larger, higher level classes like Actiniaria and 2) if it fails it should tell me why. Any chance of making it so we can get at larger sets like this?

**Comment by kevinsbarnard** [comment]
Fixed in https://github.com/kevinsbarnard/m3-download/commit/de9168b3e7cab33791b921d0952f0b6bbfdbba89. There was a bug where concepts with no localized images would cause the `generate_digest.py` script to fail. This showed up more frequently with larger sets (such as Actiniaria) as there are typically more descendant concepts.
